version: '3.8'

services:
  server:
    image: patientor-back-dev
    build:
      context: ./patientor-backend/
      dockerfile: dev.Dockerfile
    volumes:
      - ./patientor-backend/:/usr/src/app
    container_name: patientor-back-dev
  app:
    image: patientor-front-dev
    build:
      context: ./patientor-frontend/
      dockerfile: dev.Dockerfile 
    volumes:
      - ./patientor-frontend/:/usr/src/app
    container_name: patientor-front-dev
    environment:
      REACT_APP_BACKEND_URL: http://localhost:3000/api
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 3000:80
    container_name: patientor-proxy
    depends_on:
      - app
      - server
